### PR TITLE
Behaviors: Dispense dyes into sheep

### PR DESCRIPTION
**Pull request by RyanGrieb**
I think this fits into the vanilla theme of the mod. Also my eclipse messed up your formatting, hope you don't mind.

### CODE REVIEW

**Comment by cseven** [comment]
While I agree this does technically fit the vanilla theme of the mod, I don't particularly like that you've changed my formatting nor do I think there is much utility in this behavior. I think something more useful would be dying sheep directly in front of the dispenser, as that has some potential for usage.

**Comment by RyanGrieb** [comment]
> While I agree this does technically fit the vanilla theme of the mod, I don't particularly like that you've changed my formatting nor do I think there is much utility in this behavior. I think something more useful would be dying sheep directly in front of the dispenser, as that has some potential for usage.

What formatting do you use?

**Comment by cseven** [comment]
See SmartDispenserBehaviorRegistration - in the diff you can clearly see that your commits have completely redone the formatting of this file.

**Comment by RyanGrieb** [comment]
@cseven Everything should be fixed. Added sheep dyeing.

**Comment by cseven** [comment]
Great! Just took a peek through and everything looks good. Thanks for contributing!

**Pull request merged**
